services:
  mysql-db:
    image: mysql:9.6.0
    # no open host port for database (frontend url is public only)
    # uncomment to open it for testing:
    #ports:
    #  - "3307:3306"
    networks:
      - backend-network # talks to the backend only
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=planent
    volumes:
      #  mounts SQL file so Docker runs it on the first boot
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      #  saves the actual database data so it survives container restarts
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      timeout: 10s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        BACKEND_PORT: ${BACKEND_PORT}
    # no open host port for backend (frontend url is public only)
    # uncomment to open it for testing:
    #ports:
    #  - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - frontend-network # talks to frontend
      - backend-network  # talks to the database
    depends_on:
      mysql-db:
        condition: service_healthy # backend waits for database to finish booting
    volumes:
      - ./media:/app/media
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_FRONTEND_URLS=${SPRING_FRONTEND_URLS}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_GEOAPIFY_API_KEY: ${VITE_GEOAPIFY_API_KEY}
    ports:
      - "${FRONTEND_PROD_PORT}:443"
      - "80:80"
    networks:
      - frontend-network # talks to the backend only
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - APP_HOST=${APP_HOST}
      - FRONTEND_PROD_PORT=${FRONTEND_PROD_PORT}
      - PROXY_TARGET=${BACKEND_PROTOCOL}://backend:${BACKEND_PORT}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      # nginx config:
      - host=$$host
      - request_uri=$$request_uri
      - uri=$$uri
      - remote_addr=$$remote_addr
      - proxy_add_x_forwarded_for=$$proxy_add_x_forwarded_for
      - scheme=$$scheme

volumes:
  mysql-data:

networks:
  frontend-network:
  backend-network: